### ISSUE TITLE
8-band version request

### ISSUE THREAD

**Issue by MrPeterJin** [ozcelikfu/PanColorGAN#2]
Would you release the 8-band version of your method? Since this repository only has 4-band data.

**Comment by ozcelikfu** [comment]
Unfortunately, we don't have any trained model or the data for the 8-band version but if you have the data you can easily tweak some parts of the codes for training the 8-band model. Some parts of the code might be hardcoded for 4-band (You can check by searching "4" in .py files, I know there are some parts in network.py) after changing them to "8", it should definitely work.

**Comment by MrPeterJin** [comment]
Thanks, I will try it.
