### ISSUE TITLE
load pretrained model

### ISSUE THREAD

**Issue by MerakL** [ozcelikfu/PanColorGAN#3]
Hello, I would like to load your pre-trained model to train my data. I froze the generator to train only the discriminator, but I noticed that the images generated by the generator have changed even with fixed parameters. Is there any parameter that is not fixed? I am looking forward to receiving your response.

**Comment by ozcelikfu** [comment]
I don't remember all the details right now but if you want to only train the discriminator you may edit optimizerG and optimizerD accordingly. It may solve the problem
